### ISSUE TITLE
TypeError: from_generator() got an unexpected keyword argument 'args'

### ISSUE THREAD

**Issue by wlybug** [Kyubyong/transformer#100]
INFO:root:# hparams
INFO:root:# Prepare train/eval batches
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    shuffle=True)
  File "/data/wangly/python3/transformer/data_load.py", line 147, in get_batch
    batches = input_fn(sents1, sents2, vocab_fpath, batch_size, shuffle=shuffle)
  File "/data/wangly/python3/transformer/data_load.py", line 121, in input_fn
    output_types=types,args=(sents1, sents2, vocab_fpath))  # <- arguments for generator_fn. converted to np string arrays
TypeError: from_generator() got an unexpected keyword argument 'args'

**Comment by ty5491003** [comment]
Please makesure your tensorflow version is 1.12.0

**Comment by tyn513** [comment]
I got the same problem.
