### ISSUE TITLE
can this code run on a cpu machine？

### ISSUE THREAD

**Issue by echoht** [Kyubyong/transformer#109]
I run on a cpu machine with default args,   I got the following errors：
num_params:  167301123
INFO:root:Variables info has been saved.
  5%|#####5                                                                                                         | 1533/30681 [3:21:15<61:40:30,  7.62s/it]INFO:root:epoch 1 is done
INFO:root:# test evaluation
INFO:root:# get hypotheses
Traceback (most recent call last):
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[33,100] = 100 is not in [0, 100)
         [[{{node encoder_1/positional_encoding/embedding_lookup}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 81, in <module>
    hypotheses = get_hypotheses(num_eval_batches, num_eval_samples, sess, y_hat, m.idx2token)
  File "/data/gpu_codes_bak/echothuang/transformer-master/utils.py", line 144, in get_hypotheses
    h = sess.run(tensor)
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[33,100] = 100 is not in [0, 100)
         [[node encoder_1/positional_encoding/embedding_lookup (defined at /data/gpu_codes_bak/echothuang/transformer-master/modules.py:295) ]]

Caused by op 'encoder_1/positional_encoding/embedding_lookup', defined at:
  File "train.py", line 48, in <module>
    y_hat, eval_summaries = m.eval(xs, ys)
  File "/data/gpu_codes_bak/echothuang/transformer-master/model.py", line 163, in eval
    memory, sents1 = self.encode(xs, False)
  File "/data/gpu_codes_bak/echothuang/transformer-master/model.py", line 50, in encode
    enc += positional_encoding(enc, self.hp.maxlen1)
  File "/data/gpu_codes_bak/echothuang/transformer-master/modules.py", line 295, in positional_encoding
    outputs = tf.nn.embedding_lookup(position_enc, position_ind)
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 316, in embedding_lookup
    transform_fn=None)
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 133, in _embedding_lookup_and_transform
    result = _clip(array_ops.gather(params[0], ids, name=name),
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 3273, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3748, in gather_v2
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/user_00/tensorflow_env/yes/envs/tensorflow_p3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): indices[33,100] = 100 is not in [0, 100)
         [[node encoder_1/positional_encoding/embedding_lookup (defined at /data/gpu_codes_bak/echothuang/transformer-master/modules.py:295) ]]

**Comment by qyccc** [comment]
I got the same errors

**Comment by sight007** [comment]
Filling up shuffle buffer.....
.....
shuffle buffer filled.....
.....
indices[111,100]=100 is not in [0,100].......
.....

i met those errors in my CPU machine
