### ISSUE TITLE
train.py error 

### ISSUE THREAD

**Issue by EasonZhaoZ** [Kyubyong/transformer#5]
python train.py

-----   --- 

Traceback (most recent call last):
  File "train.py", line 147, in <module>
    g = Graph("train"); print("Graph loaded")
  File "train.py", line 28, in __init__
    self.decoder_inputs = tf.concat((tf.ones_like(self.y[:, :1])*2, self.y[:, :-1]), -1) # 2:<S>
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 867, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 657, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 743, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 706, in _autopacking_helper
    return gen_array_ops._pack(elems_as_tensors, name=scope)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1680, in _pack
    result = _op_def_lib.apply_op("Pack", values=values, axis=axis, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2382, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1783, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 596, in call_cpp_shape_fn
    raise ValueError(err.message)
ValueError: Dimension 1 in both shapes must be equal, but are 1 and 9
	From merging shape 0 with other shapes.

-- ------- 
how to fix this error ?

**Comment by ayanamongol** [comment]
Did you find a solution for this?

**Comment by 4pal** [comment]
did anyone find this solution?

**Comment by alfylee** [comment]
i also have this issue

**Comment by covarsha** [comment]
I have this issue as well

**Comment by weiran96** [comment]
I have the same issue, do you solve it?

**Comment by weiran96** [comment]
This is caused by your tensorflow version, and you should upgrade your tensorflow to 1.2 or higher.
