### ISSUE TITLE
python test.py --ckpt log/1 --d_model=512 --d_ff=1024  Report an error

### ISSUE THREAD

**Issue by Single430** [Kyubyong/transformer#90]
After I finished training, I ran the test.py file and reported the following error.
I have not solved it, I hope I can get your help.
@Kyubyong 

`
INFO:tensorflow:Restoring parameters from log/1/model_E04-L4.76-49080
INFO:root:# get hypotheses

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[125,100] = 100 is not in [0, 100)
	 [[{{node encoder/positional_encoding/embedding_lookup}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 54, in <module>
    hypotheses = get_hypotheses(num_test_batches, num_test_samples, sess, y_hat, m.idx2token)
  File "/mnt/data/xxxx/transformer-master/utils.py", line 144, in get_hypotheses
    h = sess.run(tensor)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[125,100] = 100 is not in [0, 100)
	 [[node encoder/positional_encoding/embedding_lookup (defined at /mnt/data/xxxx/transformer-master/modules.py:295) ]]

Caused by op 'encoder/positional_encoding/embedding_lookup', defined at:
  File "test.py", line 41, in <module>
    y_hat, _ = m.eval(xs, ys)
  File "/mnt/data/xxxx/transformer-master/model.py", line 163, in eval
    memory, sents1 = self.encode(xs, False)
  File "/mnt/data/xxxx/transformer-master/model.py", line 50, in encode
    enc += positional_encoding(enc, self.hp.maxlen1)
  File "/mnt/data/xxxx/transformer-master/modules.py", line 295, in positional_encoding
    outputs = tf.nn.embedding_lookup(position_enc, position_ind)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 316, in embedding_lookup
    transform_fn=None)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 133, in _embedding_lookup_and_transform
    result = _clip(array_ops.gather(params[0], ids, name=name),
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 3273, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3748, in gather_v2
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): indices[125,100] = 100 is not in [0, 100)
	 [[node encoder/positional_encoding/embedding_lookup (defined at /mnt/data/xxxx
/transformer-master/modules.py:295) ]]
`

**Comment by ty5491003** [comment]
The reason is your train parameters and test parameters is not equal, they need same --vocab_size --d_model & d_ff. Maybe you forgot set parameters when you running test.py.

**Comment by Single430** [comment]
@ty5491003    你好，不知道您有用过这个模型做文本摘要没，按我的理解，只需要将数据按格式对照输入，然后训练就可以，但是，当我训练出模型后，进行预测，往往在sess.run(y_hat)  时，会将我32ｇ的内存撑爆，batch_size=1,maxlen=500,d_mode=8,d_ff=64 ,请问您知道原因吗？

**Comment by ty5491003** [comment]
我没做过文本摘要，但是要使用这个模型确实是只需要将数据处理好，再设置好参数即可。你有更详细的错误提示信息吗？
@Single430

**Comment by Single430** [comment]
@ty5491003 　　就是没有错误提示，直接内存撑爆，被系统killed.  我也有训练一个德文到英语的模型，是可以正常工作的，但是我改成中文到摘要出现这个问题

**Comment by ty5491003** [comment]
@Single430 你的中文数据是否也经过了相同的预处理步骤？

**Comment by Single430** [comment]
@ty5491003 是的，我数据按照相同步骤做了操作，输入的和原来的一致

**Comment by ty5491003** [comment]
@Single430 那恕我无能为力了。不过我感觉假如你中文的输入参数设置的和德文英文一样的话那就没理由会内存不足（电脑是否有别的程序在运行？）。建议你检查一下预处理过程和预处理保存的文件，以及hparams.py的各项参数是否指向你保存的文件。

**Comment by Single430** [comment]
@ty5491003 　　　好的多谢多谢！最近跑tensor2tensor  官方例子也跑不通，这玄学

**Comment by Eric217** [comment]
> @ty5491003 　　　好的多谢多谢！最近跑tensor2tensor 官方例子也跑不通，这玄学

您好，我最近直接下载了readme里的模型，运行test报错和上面一样，如果是参数错了，那么参数是多少呢（您的模型如果是自己训练的可能也不知道原模型的参数。。可以直接邮箱2431388355@qq.com，谢谢！）

**Comment by ty5491003** [comment]
@Eric217 
我的模型是自己训练的，所以没有下载他的模型。不过你下载的模型中是否有一个hparams的文件？在训练过程中，模型参数会自动保存到这个文件里，但是我不知道下载的模型中有没有此文件。

**Comment by Eric217** [comment]
> @Eric217
> 我的模型是自己训练的，所以没有下载他的模型。不过你下载的模型中是否有一个hparams的文件？在训练过程中，模型参数会自动保存到这个文件里，但是我不知道下载的模型中有没有此文件。

没有，而且我现在硬件条件不支持我训练，所以不知道您训练的结果可不可以发我。。不胜感激！ 2431388355@qq.com

**Comment by Eric217** [comment]
> > @Eric217
> > 我的模型是自己训练的，所以没有下载他的模型。不过你下载的模型中是否有一个hparams的文件？在训练过程中，模型参数会自动保存到这个文件里，但是我不知道下载的模型中有没有此文件。
> 
> 没有，而且我现在硬件条件不支持我训练，所以不知道您训练的结果可不可以发我。。不胜感激！ [2431388355@qq.com](mailto:2431388355@qq.com)

看着手机等您回复！真的很紧急😭

**Comment by Eric217** [comment]
> @Single430 那恕我无能为力了。不过我感觉假如你中文的输入参数设置的和德文英文一样的话那就没理由会内存不足（电脑是否有别的程序在运行？）。建议你检查一下预处理过程和预处理保存的文件，以及hparams.py的各项参数是否指向你保存的文件。

在吗在吗，留言在上面，刚才@错了😭

**Comment by Eric217** [comment]
> @ty5491003 　　　好的多谢多谢！最近跑tensor2tensor 官方例子也跑不通，这玄学

这个@不知道收到了没😭，不胜感激！

**Comment by ty5491003** [comment]
@Eric217 我没有用作者的这个机器翻译的数据来训练，我是拿Transformer来做别的任务，所以我的模型没法给你直接用。

**Comment by ty5491003** [comment]
@Eric217 但是假如你真的很急用的话，我或许可以帮你训练一份作者这个机器翻译的模型。

**Comment by Eric217** [comment]
> @Eric217 但是假如你真的很急用的话，我或许可以帮你训练一份作者这个机器翻译的模型。

能用别的方式联系吗，qq2431388355或微信13176370907都可，联系后我把这些评论再删去。。

**Comment by Eric217** [comment]
能用别的方式联系吗，qq2431388355或微信 13176370907

                                                                 此致 
                                                                 敬礼

**Comment by Eric217** [comment]
@ty5491003  联系方式在上面，感谢啊！

**Comment by Eric217** [comment]
@ty5491003  如果您的机器14小时内训练不完，就算了😭。。只要是Transformer的机器翻译模型就行，数据集不限。。

**Comment by ty5491003** [comment]
@Eric217 加你微信了

**Comment by Halafz7** [comment]
> The reason is your train parameters and test parameters are not equal, they need same --vocab_size --d_model and --d_ff. Maybe you forgot set parameters when you running test.py.

Hello @ty5491003, can you explain more where i should set the parameter so the train and test parameters equal?
![image](https://user-images.githubusercontent.com/79700580/222093337-32336ac8-03c6-444d-a180-96816ee8d51d.png)

**Comment by bobobe** [comment]
Thanks，I'll reply you soon

**Comment by Halafz7** [comment]
> Thanks，I'll reply you soon

Sure! Thank you

**Comment by 61lcx** [comment]
你好，关于参数设计，我有一样的问题，能否帮我解答一下？

**Comment by bobobe** [comment]
Thanks，I'll reply you soon
