### ISSUE TITLE
KeyError when I run test.py with official model

### ISSUE THREAD

**Issue by zhuzhikui** [Kyubyong/transformer#95]
INFO:root:# get hypotheses
Traceback (most recent call last):
  File "H:/zhuzhikui/transformer/test.py", line 54, in <module>
    hypotheses = get_hypotheses(num_test_batches, num_test_samples, sess, y_hat, m.idx2token)
  File "H:\zhuzhikui\transformer\utils.py", line 146, in get_hypotheses
    hypotheses = postprocess(hypotheses, dict)
  File "H:\zhuzhikui\transformer\utils.py", line 70, in postprocess
    sent = "".join(idx2token[idx] for idx in h)
  File "H:\zhuzhikui\transformer\utils.py", line 70, in <genexpr>
    sent = "".join(idx2token[idx] for idx in h)
KeyError: 31929

**Comment by zlyq1994** [comment]
Same problem.

**Comment by e199612** [comment]
same problem.
does it has solution?
